name: Ping /run-random (Perth 07:00-24:00 only)

on:
  schedule:
    - cron: "0,30 23,0-16 * * *"
  workflow_dispatch:

jobs:
  call:
    runs-on: ubuntu-latest
    steps:
      - name: Call Render /run-random
        run: |
          http_code=$(curl -sS -o /tmp/resp.txt -w "%{http_code}" \
            -X POST "$PING_URL" \
            -H "x-trigger-token: $TRIGGER_TOKEN")
          echo "HTTP $http_code"
          cat /tmp/resp.txt
          if [[ "$http_code" != 2* && "$http_code" != 3* ]]; then
            exit 1
          fi
        env:
          PING_URL: https://auto-sortify.onrender.com/run-random
          TRIGGER_TOKEN: ${{ secrets.TRIGGER_TOKEN }}

      # 단순 재시도 1회(네트워크 흔들림 대비)
      - name: Retry once on failure
        if: failure()
        run: |
          set -euo pipefail
          sleep 15
          http_code=$(curl -sS -o /tmp/resp.txt -w "%{http_code}" \
            -X POST "$PING_URL" \
            -H "x-trigger-token: $TRIGGER_TOKEN")
          echo "HTTP $http_code"
          cat /tmp/resp.txt || true
          if [[ "$http_code" != 2* && "$http_code" != 3* ]]; then
            exit 1
          fi
        env:
          PING_URL: https://auto-sortify.onrender.com/run-random
          TRIGGER_TOKEN: ${{ secrets.TRIGGER_TOKEN }}
